---
- hosts: localhost
  tasks:
  - name: Define user details
    set_fact: 
      user_password: "{{ user_password | default(lookup('password', 'pw.user chars=ascii_letters,digits length=12')) }}"
      vde_user: "{{ vde_user | default('ubuntu') }}"
      vde_user_name: "{{ vde_user_name | default('Ubuntu') }}"

  - name: Create user group
    group:
      name: "{{ vde_user }}"
      state: present

  - name: Create user
    user:
      name: "{{ vde_user }}"
      group: "{{ vde_user }}"
      groups: adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev,lxd,netdev
      append: yes
      skeleton: /etc/skel/
      password: "{{ user_password | password_hash('sha512')"
      home: "/home/{{ vde_user }}"
      comment: "{{ vde_user_name }}"

  - name: Reset mirror for apt repos to mirrors.ubuntu.com
    replace:
      path: /etc/apt/sources.list
      regexp: 'https?://[^/]*archive\.ubuntu\.com/ubuntu/?' # Works for https://regex101.com/r/eaWr0C/2
      replace: 'mirror://mirrors.ubuntu.com/mirrors.txt'

  - name: Update OS
    apt:
      update_cache: yes
      upgrade: full
      autoremove: yes
      autoclean: yes

  - name: Setup desktop environment
    include_role:
      name: jontheniceguy.install_ubuntu_mate_vde

  - name: Setup XRDP
    include_role:
      name: jontheniceguy.install_xrdp

  - name: Setup VSCode
    include_role:
      name: jontheniceguy.install_vscode
  
  - name: Setup Virtualbox and Vagrant
    include_role:
      name: jontheniceguy.install_virtualbox_and_vagrant