---
- hosts: localhost
  tasks:
  - name: Define user details
    set_fact:
      user_password: "{{ user_password | default(lookup('password', 'pw.user chars=ascii_letters,digits length=12')) }}"
      vde_user: "{{ vde_user | default('someuser') }}"
      vde_user_name: "{{ vde_user_name | default('Some User') }}"

  - name: Create user group
    group:
      name: "{{ vde_user }}"
      state: present

  - name: Create user
    user:
      name: "{{ vde_user }}"
      group: "{{ vde_user }}"
      groups: |
        {%- if ansible_distribution == 'Ubuntu' -%}
          adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev,lxd,netdev
        {%- elif ansible_distribution == 'Fedora' -%}
          adm,wheel,systemd-journal
        {%- endif -%}
      append: yes
      skeleton: /etc/skel/
      password: "{{ user_password | password_hash('sha512') }}"
      home: "/home/{{ vde_user }}"
      comment: "{{ vde_user_name }}"

  - name: Write password file out
    copy:
      dest: /var/log/userpw
      content: |
        {{ user_password }}

      owner: root
      group: root
      mode: "0600"

  - name: Load Ubuntu tasks
    include_tasks: ubuntu.yml
    when: ansible_distribution == 'Ubuntu'

  - name: Load Fedora tasks
    include_tasks: fedora.yml
    when: ansible_distribution == 'Fedora'

  - name: Setup XRDP
    include_role:
      name: jontheniceguy.install_xrdp
    when: install_xrdp | default(false)

  - name: Setup Guacamole
    include_role:
      name: mohclips.guacamole_jumpserver
    when: install_guacamole | default(true)

  - name: Setup VSCode
    include_role:
      name: jontheniceguy.install_vscode
    when: install_vscode | default(false)

  - name: Setup Virtualbox and Vagrant
    include_role:
      name: jontheniceguy.install_virtualbox_and_vagrant
    when: install_vagrant | default(false)

  # These two items are based on
  # https://www.mydailytutorials.com/ansible-delete-multiple-files-directories-ansible/
  - name: Find files in /var/crash
    find:
      paths: /var/crash
    register: crash_files

  - name: Remove files in /var/crash
    file:
      path: "{{ item.path }}"
      state: absent
    loop: "{{ crash_files.files }}"
    loop_control:
      label: "{{ item.path }}"

  - name: Build complete. Rebooting to tidy up
    reboot:
