---
- name: Add VirtualBox Key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    id: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF

- name: Add VirtualBox Repo
  apt_repository:
    repo: "deb https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"

- name: Install VirtualBox
  apt:
    name: "virtualbox-{{ virtualbox_versions }}"
    state: latest

- name: Get Vagrant X64 Deb package
  apt:
    deb: "https://releases.hashicorp.com/vagrant/{{ vagrant_versions }}/vagrant_{{ vagrant_versions }}_x86_64.deb"
    state: present
