---
- name: Get versions
  include_tasks: version.yml

- name: Load Debian/Ubuntu tasks
  when: ansible_os_family == 'Debian'
  include_tasks: debian.yml

- name: Load RHEL/CentOS/Fedora tasks
  when: ansible_os_family == 'RedHat'
  include_tasks: rhel.yml

- name: Install Vagrant plugins
  shell: "sudo -u {{ vde_user }} vagrant plugin install {{ item }}"
  loop:
  - vagrant-cachier