---
- name: Add Virtualbox Repository
  yum_repository:
    name: virtualbox
    description: Fedora $releasever - $basearch - VirtualBox
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc

- name: Install virtualbox
  dnf:
    name:
    - "@development-tools"
    - kernel-devel
    - kernel-headers
    - dkms
    - qt5-qtx11extras
    - elfutils-libelf-devel
    - zlib-devel
    - "Virtualbox-{{ virtualbox_versions }}"
    state: present
    update_cache: yes

- name: Install Vagrant
  dnf:
    name: "https://releases.hashicorp.com/vagrant/{{ vagrant_versions }}/vagrant_{{ vagrant_versions }}_x86_64.rpm"
    state: present
