---
- name: Get latest VirtualBox version
  uri:
    url: https://download.virtualbox.org/virtualbox/debian/pool/contrib/v/
    return_content: yes
  register: virtualbox_source
  when: virtualbox_versions is not defined

- name: Define Virtualbox Version to install
  set_fact:
    virtualbox_versions: |-
      {% set ns = namespace() %}
      {%- for line in (virtualbox_source.content | default('') | string).splitlines() -%}
        {%- if 'virtualbox-' in line -%}
          {% set ns.version=line %}
        {%- endif -%}
      {%- endfor -%}
      {{ ns.version | regex_replace('^[^"]+"virtualbox-([^"]+)/".*', '\1') }}
  when: virtualbox_versions is not defined
