---
- name: Add Hashicorp Key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg

- name: Add HashiCorp Repo
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"

- name: Install Vagrant
  apt:
    name: vagrant
    state: latest
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
