---
- name: Install packages
  apt:
    name: ubuntu-mate-desktop
    state: present

- name: Fix colord issue
  copy:
    src: ../files/45-allow.colord.pkla
    dest: /etc/polkit-1/localauthority/50-local.d/45-allow.colord.pkla