---
- name: Load Debian tasks
  when: ansible_distribution == 'Debian'
  include_tasks: debian.yml

- name: Load Ubuntu tasks
  when: ansible_distribution == 'Ubuntu'
  include_tasks: ubuntu.yml

- name: Load CentOS tasks
  when: ansible_distribution == 'CentOS'
  include_tasks: centos.yml

- name: Load Fedora tasks
  when: ansible_distribution == 'Fedora'
  include_tasks: fedora.yml

- name: Add user to Docker group
  user:
    append: yes
    name: "{{ vde_user }}"
    groups: docker