---
- name: Ensure dependencies installed
  apt:
    name: xz-utils
    state: present
  register: apt_action
  retry: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Install VSCode
  apt:
    deb: https://vscode-update.azurewebsites.net/latest/linux-deb-x64/stable
    state: present
  register: apt_action
  retry: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
