---
- name: Load Ubuntu tasks
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  include_tasks: ubuntu.yml

- name: Load Fedora tasks
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Fedora' or ansible_distribution == 'Red Hat Enterprise Linux'
  include_tasks: rhel.yml
