pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/host.crt
  key: /etc/nebula/host.key

static_host_map:
{% for lighthouse in nebula_lighthouses | default([]) %}
  "{{ lighthouse.nebula_ip }}": {% if lighthouse.public_ips | default('') | length == 0 %}[]{% endif %}

{% for public_ip in lighthouse.public_ips | default([]) %}
  - "{{ public_ip }}"
{% endfor %}
{% endfor %}

lighthouse:
  am_lighthouse: {{ nebula_am_lighthouse | default('false') }}
  interval: 60
  hosts: {% if nebula_am_lighthouse | default('false') != 'false' %}[]{% else %}

{% for lighthouse in nebula_lighthouses | default([]) %}
  - "{{ lighthouse.nebula_ip }}"
{% endfor %}
{% endif %}

listen:
  host: {{ nebula_host | default('0.0.0.0') }}
  port: {{ nebula_port | default('4242') }}

punchy:
  punch: true
  respond: true
  delay: 1s

sshd:
  enabled: true
  listen: 127.0.0.1:2222
  host_key: /etc/ssh/ssh_host_ed25519_key
  authorized_users: {% if nebula_ssh_users | default('') | length == 0 %}[]{% else %}

{% for nebula_ssh_user in nebula_ssh_users | default([]) %}
    - user: "{{ nebula_ssh_user.username }}"
      keys: {% if nebula_ssh_user.keys | default('') | length == 0 %}[]{% else %}

{% for nebula_key in nebula_ssh_user.keys | default([]) %}
        - "{{ nebula_key }}"
{% endfor %}
{% endif %}
{% endfor %}
{% endif %}

tun:
  disabled: {{ nebula_tun_disabled | default('false') }}
  dev: {{ nebula_tun_name | default('nebula1') }}
  drop_local_broadcast: {{ nebula_drop_local_broadcast | default('true') }}
  drop_multicast: {{ nebula_drop_local_multicast | default('true') }}

firewall:
  outbound:
{% for rule in nebula_outbound | default([{'port': 'any', 'proto': 'any', 'host': 'any'}]) %}
  - {{ rule }}
{% endfor %}

  inbound:
{% for rule in nebula_inbound | default([{'port': 'any', 'proto': 'any', 'host': 'any'}]) %}
  - {{ rule }}
{% endfor %}